sudo: true
language: node.js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - "node_modules"
install:
  - npm i gem
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn 
script:
  - npm test jest/test/index.test.js
  - npm test jest/test/insultGenerator.test.js
  dist: trusty 
addons: 
  chrome: stable  