sudo: true
language: node.js
node_js:
  - "stable"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - nvm install # Install node version from .nvmrc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - gem update --system
  - gem install bundler -v 1.16.1
install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
  - npm i gem
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script: bundle exec rake db:create db:migrate
script:
  - "bundle exec rspec $jest/test"
