sudo: true
language: node.js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "jest"
install:
  - bundle install
  - npm i gem
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - cd jest
  - npm test --coverage
