sudo: true
language: node.js
node_js:
  - "stable"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - npm i gem
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - cd jest
  - ./jest/test/index.test.js
