sudo: true
language: node.js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - "node_modules"
    - "jest"
install:
  - npm i gem
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  "test": "./node_modules/gulp/bin/gulp.js test"
